services:
  moviepilot-ai-recognizer-gateway:
    image: liuyuexi1987/moviepilot-ai-recognizer-gateway:2.0.0-alpha.1
    container_name: moviepilot-ai-recognizer-gateway
    env_file:
      - .env
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - moviepilot

networks:
  moviepilot:
    external: true
    name: moviepilot
